/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ced_oop;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;

/**
 *
 * @author dell
 */
public class NewJFrame1 extends javax.swing.JFrame {
 private static DefaultTableModel tableModel;
 String a;
    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
         initComponents();
        setLocationRelativeTo(null);
    }
    public NewJFrame1(String a) {
        this.a=a;
    }
    String returner()
    {
        return a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
      Frame o=new Frame();
      o.setBounds(400, 400, 700, 300);
        NewJFrame1 ui=new NewJFrame1();
      String path= ui.returner();
      System.out.println(path);
          File f=new File(path);
        Workbook wb=Workbook.getWorkbook(f);
        Sheet s=wb.getSheet(0);
        int row=s.getRows();
        int col=s.getColumns();
         String data[]=new String[col];
         String  columnNames[][]=new String[row][col];
        for(int i=0;i<row;i++)
        {
            for(int j=0;j<col;j++)
            {
                if(i==0)
                {
                 Cell c=s.getCell(j,i);
                 data[j]=c.getContents();
                }
                else{
                 Cell c=s.getCell(j,i);
               columnNames[i][j]=c.getContents();
                }
                
             }
        }
       JTable table = new JTable(columnNames,data);
           table.setBounds(25, 25, 650, 250);
           JScrollPane sp=new JScrollPane(table);  
           sp.setBounds(25, 25, 650, 250);
        o.add(sp);
       Button be=new Button();
       be.setLabel("Print");
       be.setBounds(300, 300, 35, 35);
           be.addActionListener(new ActionListener(){  
public void actionPerformed(ActionEvent e){  
    try {
        table.print();
    } catch (PrinterException ex) {
        Logger.getLogger(NewJFrame1.class.getName()).log(Level.SEVERE, null, ex);
    }
        }  
    });  
       o.add(be);
        o.show();
    }
/*
    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
